Introduces ActiveJobSubscriber
InfluxCommunity/influxdb-rails pull request #102
Opened 2020-02-12 21:02 UTC by hennevogel

2020-02-12 21:08 UTC, hennevogel commented
Need to come up with a clever way to test this. I was thinking of emitting some mocked `ActiveSupport::Notifications` on another route like `/active_job`. What do you think?

2020-02-12 21:18 UTC, ChrisBr requested changes
> I was thinking of emitting some mocked ActiveSupport::Notifications on another route, like /active_job. What do you think?

Why not just creating a real active job? Would be too much overhead?

2020-02-12 21:18 UTC, ChrisBr commented on lib/influxdb/rails/middleware/active_job_subscriber.rb
> +          value = short_hook_name == "perform.active_job" ? duration : "1"
Can we do something like `succeeded?`?

2020-02-12 21:18 UTC, ChrisBr commented on lib/influxdb/rails/middleware/active_job_subscriber.rb
> +            queue: payload[:job].queue_name,
Can this be a whiny nil? Should we do `payload[:job]&.queue_name`?

2020-02-12 21:29 UTC, hennevogel commented on lib/influxdb/rails/middleware/active_job_subscriber.rb
> +          value = short_hook_name == "perform.active_job" ? duration : "1"
You mean like 

```ruby
def measure_performance?
  short_hook_name == "perform.active_job"
end
```

2020-02-12 21:30 UTC, hennevogel commented on lib/influxdb/rails/middleware/active_job_subscriber.rb
> +            queue: payload[:job].queue_name,
Nope can't be, I don't see how as this always comes from `ActiveJob`

2020-02-12 21:33 UTC, hennevogel commented
> Why not just creating a real active job? Would be too much overhead?

The job is not the problem, mocking the backend is.

2020-02-12 21:36 UTC, hennevogel commented on lib/influxdb/rails/middleware/active_job_subscriber.rb
> +            queue: payload[:job].queue_name,
Also never seen this in production...

2020-02-12 21:38 UTC, hennevogel commented on lib/influxdb/rails/middleware/active_job_subscriber.rb
> +          value = short_hook_name == "perform.active_job" ? duration : "1"
please have another look

2020-02-12 22:02 UTC, ChrisBr commented on lib/influxdb/rails/middleware/active_job_subscriber.rb
> +            queue: payload[:job].queue_name,
Okay.

Just wondering what would happen if you delete a job class and still have some enqueued 🤔

2020-05-07 14:37 UTC, ChrisBr approved these changes

2020-05-07 14:38 UTC, ChrisBr commented
@hennevogel added some specs, what do you think? The async backend does trigger enqueue, start and perform jobs so I think we're good.

2020-05-11 13:42 UTC, merged