Several refactorings
InfluxCommunity/influxdb-rails pull request #103
Opened 2020-02-12 21:04 UTC by ChrisBr

This PR adds some more specs around exceptions and refactors some of the code. The commits should be self explanatory.

2020-02-12 21:05 UTC, ChrisBr commented
dd37365 will get fixed with https://github.com/influxdata/influxdb-rails/pull/101 and can get dropped after it is merged.

2020-05-04 16:32 UTC, hennevogel requested changes

2020-05-04 16:32 UTC, hennevogel commented on spec/support/broken_client.rb
> +require "launchy"
launchy?

2020-05-04 16:32 UTC, hennevogel commented on lib/influxdb/rails/railtie.rb
> +        ActiveSupport::Notifications.subscribe "process_action.action_controller", &reset_cache
I find this less clear. What's the reason to move it here?

2020-05-04 20:29 UTC, ChrisBr commented on lib/influxdb/rails/railtie.rb
> +        ActiveSupport::Notifications.subscribe "process_action.action_controller", &reset_cache
Don't remember why I moved it to the Railties so I moved it back.

2020-05-05 11:04 UTC, hennevogel approved these changes

2020-05-05 11:04 UTC, merged