Implement instantiation.active_record subscriber
InfluxCommunity/influxdb-rails pull request #104
Opened 2020-02-20 11:32 UTC by ChrisBr

Partially address https://github.com/influxdata/influxdb-rails/issues/74

https://guides.rubyonrails.org/active_support_instrumentation.html#instantiation-active-record

2020-02-20 11:34 UTC, ChrisBr commented on lib/influxdb/rails/middleware/active_record_subscriber.rb
> +            hook:       "instantiation",
Not sure if I like this 🤔 Maybe we need to think about differentiate better between AR SQL and AR instantiation.

2020-05-04 16:40 UTC, hennevogel commented on lib/influxdb/rails/middleware/active_record_subscriber.rb
> +            hook:       "instantiation",
You should take this up with AR then, their naming and we should stick to it :smile:

2020-05-04 16:45 UTC, hennevogel requested changes

2020-05-04 16:45 UTC, hennevogel commented on lib/influxdb/rails/middleware/active_record_subscriber.rb
> +            value:        ((finished - started) * 1000).ceil,
We moved this to `Subscriber.call` now

2020-05-04 16:52 UTC, hennevogel commented on lib/influxdb/rails/middleware/active_record_subscriber.rb
> +            value:        ((finished - started) * 1000).ceil,
Ah damn this is in #102 lol

2020-05-04 16:54 UTC, hennevogel commented
If you rebase this is good to go

2020-05-04 19:08 UTC, ChrisBr commented on lib/influxdb/rails/middleware/active_record_subscriber.rb
> +            hook:       "instantiation",
What I mean is that we have no prefix in our `hook` tag which means it's just `instantiation`.  So what kind of instantiation? Any class? ActiveRecord class? The original hook name is `active_record.instantiation` but we decided at some point to not include the prefix anymore.

2020-05-05 11:22 UTC, hennevogel commented on lib/influxdb/rails/middleware/active_record_subscriber.rb
> +            hook:       "instantiation",
Yes we did, to make our queries cleaner, that's the price we pay.

However, there is only one match for `instantiation` in the ASI docu, so this is fine IMHO.

https://guides.rubyonrails.org/active_support_instrumentation.html

2020-05-05 11:22 UTC, hennevogel approved these changes

2020-05-05 11:22 UTC, merged