Instantiate middleware
InfluxCommunity/influxdb-rails pull request #118
Opened 2020-05-13 22:48 UTC by ChrisBr

So far we only created one instance of the middleware and then operated on this instance. This made the code quite ugly because we always needed to pass around the method parameters from method to method. This PR creates now a new instance for each request.

The main part what I changed is basically from

```ruby
class Subscriber
  def call(name, start, finish, payload)
  end
end
```

to

```ruby
class Subscriber
  def self.call(name, start, finish, payload)
    new(name, start, finish, payload)
  end
end
```

In my opinion this makes the code a lot nicer to work with because we can easily extract helper methods and memoize values. This refactoring is a preparation for https://github.com/influxdata/influxdb-rails/issues/117 which made it quite hard to squeeze more code without the ability to have helper methods.

Downside of this approach is of course that we create a few more instances per request but I think this is worth it.

2020-07-18 16:32 UTC, hennevogel requested changes

2020-07-18 16:32 UTC, hennevogel commented on lib/influxdb/rails/railtie.rb
> +          subscribe_to(hook_name, subscriber)
I don't think the `subscribe_to` method brings any clarity anymore.

2020-07-18 16:32 UTC, hennevogel commented on lib/influxdb/rails/middleware/sql_subscriber.rb
> +          super || !query.track?
OR?

2020-07-19 17:27 UTC, ChrisBr commented on lib/influxdb/rails/middleware/sql_subscriber.rb
> +          super || !query.track?
Yes if super does disable it or we don't track the query.

Tests proof that I'm right I guess 😉 

Super does implement

```ruby
def disabled?
  configuration.ignore_current_environment? ||
    configuration.ignored_hooks.include?(hook_name)
 end
```

See `Subscriber` class.

2020-07-19 17:27 UTC, ChrisBr commented on lib/influxdb/rails/railtie.rb
> +          subscribe_to(hook_name, subscriber)
Yeah good point 👍 Lets get rid of it!

2020-07-19 17:47 UTC, hennevogel commented on lib/influxdb/rails/middleware/sql_subscriber.rb
> +          super || !query.track?
ok

2020-07-20 08:11 UTC, merged