Support InfluxDB 2.0
InfluxCommunity/influxdb-rails pull request #160
Opened 2021-02-14 15:18 UTC by ChrisBr

Initial support for InfluxDB > 1.8.

## Client config

Should we remove the whole client config and just let people set the client. Don't see much value in storing the config and just hand it down to the client and we will always need chase the client config.

```ruby
InfluxDB::Rails.client = InfluxDB2::Client.new()
```

## Default values

The new client lib supports default values. Should we just get rid of them here then?

2021-02-14 18:00 UTC, ChrisBr commented
No idea why the tests fail, they work locally for me.

Also there is an issue with the timestamps https://github.com/influxdata/influxdb-client-ruby/issues/68

2021-02-15 21:46 UTC, hennevogel commented
> No idea why the tests fail, they work locally for me.

Go find out :wink:

2021-02-15 21:51 UTC, hennevogel requested changes

2021-02-15 21:51 UTC, hennevogel commented on lib/influxdb/rails/middleware/request_subscriber.rb
> -          InfluxDB.convert_timestamp(
I'm supposed to take care of this myself now?

2021-02-15 21:56 UTC, hennevogel commented
> InfluxDB::Rails.client = InfluxDB2::Client.new()

Hmmm. Not sure it's fair to leave people completely alone with this. I mean, unlike us, they come from the other direction you know? Just looking for some instrumentation...

2021-02-15 23:38 UTC, ChrisBr commented
> Hmmm. Not sure it's fair to leave people completely alone with this. I mean, unlike us, they come from the other direction you know? Just looking for some instrumentation...

Okay, makes sense. We have to update the config then though.

2021-02-15 23:41 UTC, ChrisBr commented on lib/influxdb/rails/middleware/request_subscriber.rb
> -          InfluxDB.convert_timestamp(
No the influxdb-client-ruby gem does it now. You have to pass in the precision when creating the client.

We either have to do a mapping from our symbols or let people set these constants here too.

```ruby
client = InfluxDB2::Client.new('https://localhost:8086', 'my-token',
  bucket: 'my-bucket',
  org: 'my-org',
  precision: InfluxDB2::WritePrecision::NANOSECOND)
```

https://github.com/influxdata/influxdb-client-ruby#creating-a-client

2021-02-15 23:43 UTC, ChrisBr commented
@hennevogel do you want to create a new branch from the current master like 1.0-stable and develop 2.0 on master?

2021-02-16 11:03 UTC, hennevogel commented on lib/influxdb/rails/middleware/request_subscriber.rb
> -          InfluxDB.convert_timestamp(
So the client converts internally then? cool

2021-02-16 11:04 UTC, hennevogel commented
> do you want to create a new branch from the current master like 1.0-stable and develop 2.0 on master?

Yeah, sounds like a plan.

2021-02-16 11:05 UTC, hennevogel commented
> Okay, makes sense. We have to update the config then though.

Well maybe it's enough to provide sensible defaults in the generator?

2021-02-28 12:33 UTC, ChrisBr commented on README.md
> +    InfluxDB::Rails.current.fields = { redis_value: redis_value }
Should we make this backward compatible or break because it's a major update?

2021-02-28 12:34 UTC, ChrisBr commented on lib/influxdb-rails.rb
> +            bucket:        cfg.bucket,
This will be a breaking change.

2021-02-28 12:36 UTC, ChrisBr commented on lib/influxdb-rails.rb
> +            precision:     cfg.precision,
Should we keep `time_precision` or follow the upstream config?

2021-02-28 12:36 UTC, ChrisBr commented on lib/influxdb/rails/configuration.rb
> +          max_retries: retries
Should we follow upstream or keep the same config?

2021-02-28 12:40 UTC, ChrisBr commented on lib/influxdb/rails/configuration.rb
> +          max_retries: max_retries
Should we follow upstream configuration or keep `retries`? I also find `max_retries` more descriptive.

2023-06-28 17:48 UTC, antonengelhardt commented
@ChrisBr Are you planning to complete work on this PR? We'd really love to have support for Influx > 2.0, preferably 2.7. Thanks!

2023-07-03 08:55 UTC, ChrisBr commented
Not actively working on it but happy to review a pull request!

2023-07-14 11:12 UTC, araslanov-e commented
@hennevogel please add support for 2.0

2023-07-18 17:58 UTC, hennevogel commented on README.md
> +    InfluxDB::Rails.current.fields = { redis_value: redis_value }
There isn't much backward compatibility between Influx 1.x and 2.x, I don't think we should be the exception.

2023-07-18 17:58 UTC, hennevogel commented on lib/influxdb-rails.rb
> +            precision:     cfg.precision,
follow the upstream

2023-07-18 17:58 UTC, hennevogel commented on lib/influxdb/rails/configuration.rb
> +          max_retries: retries
follow upstream

2023-07-18 17:59 UTC, hennevogel commented on lib/influxdb/rails/configuration.rb
> +          max_retries: max_retries
follow upstream

2023-07-18 18:01 UTC, hennevogel commented on lib/influxdb-rails.rb
> +            bucket:        cfg.bucket,
This is InfluxDB 2.x!

![BREAK AND DANCE](https://media.giphy.com/media/jTBGVjRMxXrMEk7oVn/giphy.gif)

2023-07-18 20:15 UTC, hennevogel approved these changes
Here we go!

2023-07-18 20:15 UTC, hennevogel commented
Now on to the documentation....

2023-07-18 20:16 UTC, merged

2023-07-31 13:51 UTC, antonengelhardt commented
Thanks a lot! @ChrisBr @hennevogel