Do not reject FalseClass from tags/values
InfluxCommunity/influxdb-rails pull request #171
Opened 2021-04-12 13:29 UTC by hennevogel

false is blank

Loading production environment (Rails 6.0.3.6)
[1] pry(main)> false.blank?
=> true

2021-04-12 13:31 UTC, hennevogel commented
```ruby
[1] pry(main)> blah = false
=> false
[2] pry(main)> blah && blah.blank?
=> false
[3] pry(main)> blah = ''
=> ""
[4] pry(main)> blah && blah.blank?
=> true
[5] pry(main)> blah = []
=> []
[6] pry(main)> blah && blah.blank?
=> true
[7] pry(main)> blah = :hans
=> :hans
[8] pry(main)> blah && blah.blank?
=> false
[9] pry(main)> blah = 'hans'
=> "hans"
[10] pry(main)> blah && blah.blank?
=> false
```

2021-04-12 13:59 UTC, danidoni approved these changes

2021-04-12 15:07 UTC, ChrisBr requested changes

2021-04-12 15:07 UTC, ChrisBr commented on lib/influxdb/rails/tags.rb
> +          value && value.blank?
```ruby
irb(main):028:0> {key: nil}.reject { |_, v| v && v.blank? }
=> {:key=>nil}
```

2021-04-12 15:09 UTC, ChrisBr commented on lib/influxdb/rails/tags.rb
> +          value && value.blank?
```ruby
expanded_tags.reject do |_, value|
  return true unless value

  value.blank?
end
```

2021-04-12 15:12 UTC, ChrisBr commented on spec/support/rails5/app.rb
> +    InfluxDB::Rails.current.values = { additional_value: :value, empty_array: [], empty_string: "  ", custom_value: %w[a b] }
We should test for a `nil` value.

Although usually I'm for high level tests, I think in this case I would probably prefer a unit test.

```ruby
it 'removes nil values' do
  expect(Tags.new({ key: nil }).to_h).to be empty
end

it 'removes empty string values' do
  expect(Tags.new({ key: '   ' , string: ' }).to_h).to be empty
end
  
```

2021-04-12 16:06 UTC, hennevogel commented on lib/influxdb/rails/tags.rb
> +          value && value.blank?
```ruby
expanded_tags.reject do |_, value|
  return true if value.is_a?(FalseClass)

  value.blank?
end
```

2021-04-13 11:23 UTC, hennevogel commented
@ChrisBr made this a bit more explicit and spec'ed out `Value`. Please re-review

2021-04-13 13:04 UTC, ChrisBr approved these changes

2021-04-13 13:04 UTC, ChrisBr commented on spec/unit/tags.rb
> +      expect(subject.to_h).to a_hash_including(hans: true)
[nit] IIRC `a_hash_including` / `hash_including` are just alias for `include` which reads a lot nicer in this case.

```suggestion
      expect(subject.to_h).to include(hans: true)
```

https://gist.github.com/JunichiIto/f603d3fbfcf99b914f86

2021-04-13 13:13 UTC, hennevogel commented on spec/unit/tags.rb
> +      expect(subject.to_h).to a_hash_including(hans: true)
I think they invented `a_hash_including` because it reads nicer and produces better error messages hehe

2021-04-13 13:14 UTC, hennevogel commented on spec/unit/tags.rb
> +      expect(subject.to_h).to a_hash_including(hans: true)
https://rspec.info/blog/2014/01/new-in-rspec-3-composable-matchers/#matcher-aliases

2021-04-13 13:26 UTC, merged