Add `cached` key for active_record payloads
InfluxCommunity/influxdb-rails pull request #225
Opened 2024-05-27 10:28 UTC by eduardoj

2024-05-27 10:39 UTC, hennevogel requested changes

2024-05-27 10:39 UTC, hennevogel commented on lib/influxdb/rails/middleware/sql_subscriber.rb
> +            cached:     query.cached,
As far as I understood the documentation

> true is added when cached queries used

So can you make this a boolean tag? Otherwise it'll also be indistinguishable from measurements that did not track this tag.

2024-05-27 11:46 UTC, eduardoj commented on lib/influxdb/rails/middleware/sql_subscriber.rb
> +            cached:     query.cached,
> As far as I understood the documentation
> 
> > true is added when cached queries used
> 
> So can you make this a boolean tag? Otherwise it'll also be indistinguishable from measurements that did not track this tag.

You mean something similar to this? `cached: query&.cached == 'true',`.

2024-05-27 14:16 UTC, hennevogel approved these changes

2024-05-28 10:20 UTC, eduardoj commented
@hennevogel, I rebased on master and changed the code to:

```ruby
cached: query.try(:cached) == "true"
```

Please take a look again.

2024-05-28 10:35 UTC, hennevogel commented on spec/requests/active_record_sql_metrics_spec.rb
> +        cached:     false
Hm, in reality this is not set right if it's not cached. That's why we do query.try(:cached) == "true" above...

2024-05-28 10:39 UTC, eduardoj commented on spec/requests/active_record_sql_metrics_spec.rb
> +        cached:     false
> Hm, in reality this is not set if it's not cached right?. That's why we do query.try(:cached) == "true" above...

Nop. With the changes proposed, from now on `cached` will always be set, either to `false` or `true`. If the query is not cached, it will be set to `false`.

2024-05-28 10:43 UTC, hennevogel commented on spec/requests/active_record_sql_metrics_spec.rb
> +        cached:     false
Ah true, sorry I was confused....

2024-05-28 10:44 UTC, hennevogel approved these changes

2024-05-28 10:45 UTC, merged