Added config parameter to configure app name …
InfluxCommunity/influxdb-rails pull request #44
Opened 2018-02-01 15:41 UTC by stefanhorning

used for tagging the rails metrics to be able to distinguish between multiple apps.

2018-02-01 15:52 UTC, dmke requested changes
The default value for `app_name` should not be `my-rails-app`. Existing users of this gem, who haven't set this, shouldn't start to wonder where this might have came from.

I'd suggest either to re-use the application class name, or default to a blank value.

2018-02-01 15:52 UTC, dmke commented on lib/influxdb/rails/configuration.rb
> +        :rails_app_name => 'my-rails-app',
This should either be `nil`, or something like `Rails.application.class.parent_name`.

2018-02-01 15:52 UTC, dmke commented on lib/influxdb-rails.rb
>              },
`app_name` might be blank, so you'll need a `.compact` on the hash

2018-02-01 15:52 UTC, dmke commented on lib/influxdb-rails.rb
>              },
same here

2018-02-01 15:52 UTC, dmke commented on lib/influxdb-rails.rb
>              },
and here

2018-02-01 16:11 UTC, stefanhorning commented
Yes, was thinking the same thing. Just wanted to quickly check first if this change flies. Will implement the rest tomorrow.

2018-02-02 11:04 UTC, stefanhorning commented
Now done, complete with specs.

2018-02-02 11:07 UTC, dmke commented
LGTM, will merge it later, when I'm back home.

2018-02-02 11:10 UTC, stefanhorning commented
Perfect, thanks!

2018-02-12 12:22 UTC, stefanhorning commented
Tests seem to fail for **some** Ruby versions, not sure why as those are unrelated to my changes.

2018-02-12 19:30 UTC, dmke commented
Hm, usually restarting the Travis job helps, but in this case it didn't...

(btw. I totally forgot about this, but I'm on it now :-))

2018-02-12 19:53 UTC, dmke commented
Interestingly, with the exact same gemset from the [last succeeding spec run](https://travis-ci.org/influxdata/influxdb-rails/jobs/336505417), your changes still fail locally... I'm not sure, *why* this happens (and only for Ruby < 2.4 for Rails 4.0), but I agree, these failures *should* be unrelated to your changes.

2018-02-12 20:19 UTC, dmke commented
Got it. `Hash#compact` is undefined. Could've sworn, that existed in Rails 4.0...

2018-02-12 20:51 UTC, stefanhorning commented
I see. Should I find another solution or will you fix it?

2018-02-12 22:58 UTC, stefanhorning commented
Fixed now, by no longer relying on ´#compact´.

2018-02-12 23:05 UTC, dmke commented
This is now merged in fae86f0 and c1f144d. The workaround for `Hash#compact` can be found in 6234e1c.

I've not yet released a new gem version, since I started a major refactoring and want to include #22 and #43 as well. Since 055a952 introduced some breaking changes and at least #43 requires more of them, I'm going for a 1.0 release.

2018-02-12 23:05 UTC, closed without merging

2018-02-18 13:59 UTC, dmke commented
After some cleanup, I've discovered [`config.application_name`](https://github.com/influxdata/influxdb-rails/blob/master/lib/influxdb/rails/configuration.rb#L27), which actually gets already set to `Rails.application.class.parent_name` [in the Railtie](https://github.com/influxdata/influxdb-rails/blob/master/lib/influxdb/rails/railtie.rb#L18).

I'm going to remove `rails_app_name` from the configuration and use the value of `application_name` instead.