Add method, status and format tags to metrics
InfluxCommunity/influxdb-rails pull request #50
Opened 2018-11-21 13:56 UTC by ChrisBr

These values are provided by the payload anyway
and will allow very interesting queries like

* group / count only successfull requests
* group / count only GET requests
* group / count only JSON requests

I think these tags should be included by default because they're potentially interesting for all users.

2018-11-21 14:02 UTC, ChrisBr commented
We could also include ``path`` to partly solve #30.

2018-11-21 23:15 UTC, dmke requested changes
Some styling issues, but looks good.

2018-11-21 23:15 UTC, dmke commented on lib/influxdb-rails.rb
> +          path:     payload[:path],
Please keep values aligned.

2018-11-21 23:15 UTC, dmke commented on spec/unit/influxdb_rails_spec.rb
> +          app_name: 'my-rails-app'
Same here, please align values. Also keep the trailing comma.

2018-11-22 08:39 UTC, ChrisBr commented
@dmke thanks for the feedback, updated!

2018-11-22 09:02 UTC, dmke approved these changes

2018-11-22 09:03 UTC, dmke commented
Thanks, I'll merge it later when I'm back home.

2018-11-22 09:04 UTC, ChrisBr commented
> Thanks, I'll merge it later when I'm back home.
 
Can we expect a new version release soon?

2018-11-22 09:06 UTC, dmke commented
Immediately after. :-)

2018-11-22 09:09 UTC, ChrisBr commented
> Immediately after. :-)

Awesome :+1: Thanks for your great work :heart: 

Btw, is there somewhere documentation etc for creating grafana dashboards out of this data? We still struggle to create a good dashboard ...

2018-11-22 21:06 UTC, dmke commented
I've merged your changes into a 1.0-beta branch (78d39f8...ed785c7), because I forgot that I have a pending 1.0 release.

So far, Travis looks good (https://travis-ci.org/influxdata/influxdb-rails/builds/458571410). When this finishes, I'll issue a beta release.

2018-11-22 21:06 UTC, closed without merging