Sql subscriber
InfluxCommunity/influxdb-rails pull request #55
Opened 2018-11-30 10:31 UTC by ChrisBr

ActiveSupport instrumentation sql.active_record events are getting
now also written into the InfluxDB.

Therefore the RenderSubscriber was splitted into a base class
which gets reused in the SqlSubscriber.

The queries also getting normalized from parameters first, e.g.
'SELECT * FROM posts where id = 42' becomes
'SELECT * FROM posts where id = xxx'. This idea was shameless copied
from http://stevenyue.com/blogs/tracking-sql-queries-in-rails/.

https://guides.rubyonrails.org/active_support_instrumentation.html#sql-active-record

This got extracted #53 and needs to get rebased as soon as #53 is merged.

2018-11-30 10:37 UTC, ChrisBr commented
> I'll sample a few queries from a few different Rails apps I've access to, and throw it against your normalizer. I suspect the interesting queries (those with sub-sejects, joins, and/or group-by clauses) are going to be boiled down too much. I fear that the simple regex is both too simple has a too large CPU footprint (I've seen hundrets of queries on a single page).

That would be great. As said, maybe I can also run it for a few days on our server. With the path element we pretty quickly experienced that it is not usable as a tag.

>> Skylight does something similar, they combine it with the partial and view results

> That looks to me, as if the omit the conditions from the query (I see select from venues, but no select from venue where x in (y). This suggests two tags (table_name and op).

Hm, right. I will maybe dig a little into the skylight gem to see how they normalize the queries.

2018-11-30 13:01 UTC, ChrisBr commented
Ok, seems skylight indeed does only store operation and table:

```ruby
require 'skylight'

result = Skylight.lex_sql("SELECT name FROM users WHERE id = 42")
puts result.inspect
# => ["SELECT FROM users", "SELECT name FROM users WHERE id = ?"]
```

Additionally they do the normalization in a C extension. So I agree that we follow your suggestion to store operation and table as tags and the normalized query as a field value.

Question: Do you think the regex will really be a problem performance wise? Do you have any other suggestion (except writing a C extension as well?). Or we just go ahead with the regex for now and implement a switch to disable this metric (e.g. when setting the series_name to nil / ""). What do you think?

2018-11-30 22:57 UTC, dmke commented
> Additionally they do the normalization in a C extension. So I agree that we follow your suggestion to store operation and table as tags and the normalized query as a field value.

:+1: 

> Question: Do you think the regex will really be a problem performance wise? Do you have any other suggestion (except writing a C extension as well?). Or we just go ahead with the regex for now and implement a switch to disable this metric (e.g. when setting the series_name to nil / ""). What do you think?

I'd prefer not to write and/or maintain C extensions. Having an off-switch for a regex-based query instrumentation sounds great – but I'd have this feature disabled by default, where the consumer needs to opt-in.

2018-12-01 15:26 UTC, ChrisBr commented
> I'd prefer not to write and/or maintain C extensions. Having an off-switch for a regex-based query instrumentation sounds great – but I'd have this feature disabled by default, where the consumer needs to opt-in.

@dmke ok, I will implement this as soon as #53 is implemented.

2018-12-02 17:30 UTC, ChrisBr commented
@dmke Rebased and implemented your feedback:

* SQL reports are disabled by default
* We report now sql operation, class name and name
* The normalized query gets stored as an additional value :sql

Please have a look again, thanks :+1:

2018-12-02 20:42 UTC, dmke requested changes
Again, some nitpicks. I'm not sure whether the `SimpleSubscriber` class add an unnecessary level of abstraction... let me think about this a bit.

2018-12-02 20:42 UTC, dmke commented on README.md
> +intensive applications. You can enable it by setting the ``series_name_for_sql``
```diff
- ``series_name_for_sql``
+ `series_name_for_sql`
```

2018-12-02 20:42 UTC, dmke commented on lib/influxdb/rails/middleware/request_subscriber.rb
> +                                                 tags:      tags(payload),
Please keep the optimization introduced in 1734e4fac98708a92511a1f97084daf232e13cfb.

2018-12-02 20:42 UTC, dmke commented on spec/unit/sql/query.rb
> +    it { expect(described_class.new("INSERT").table_name).to be true }
This seems to confuse `track?` with `table_name`.

2018-12-02 20:42 UTC, dmke commented on lib/influxdb/rails/middleware/simple_subscriber.rb
> +        def time_stamp(finished)
Please use `timestamp`, not `time_stamp`.

2018-12-02 20:58 UTC, ChrisBr commented on spec/unit/sql/query.rb
> +    it { expect(described_class.new("INSERT").table_name).to be true }
You're right ... and it was not even executed because of the missing `_spec.rb` postfix :man_facepalming:

2018-12-02 21:01 UTC, ChrisBr commented
@dmke fixed

> I'm not sure whether the SimpleSubscriber class add an unnecessary level of abstraction... let me think about this a bit.

Hm, I see you ... however, the render and sql subscriber share quite some functionality :thinking: I was even thinking about moving everything into the Subscriber class and just overwrite the call method in ``RequestSubscriber`` as this potentially is the only subscriber which sends several datapoints to Influx. All other subscriber send a single data point. Or maybe we also split the request subscriber into just sending a single datapoint but subscribe it three times instead? Might be a little cleaner ...

2018-12-02 21:09 UTC, dmke commented
> `RequestSubscriber` [...] is the only subscriber which sends several datapoints to Influx.
> [...] split the request subscriber into just sending a single datapoint but subscribe it three times instead? Might be a little cleaner ...

Cleaner maybe, but this would be unnecessary implementation work for a temporary workaround. Pending #56, I'd like to resolve this in the next week, so you don't need to touch this ;-)

2018-12-02 21:12 UTC, dmke commented on spec/unit/sql/query.rb
> +    it { expect(described_class.new("INSERT").table_name).to be true }
A shame Rubocop didn't catch that, whilst it complains about *everything* else :-D

2018-12-02 21:18 UTC, ChrisBr commented on spec/unit/sql/query.rb
> +    it { expect(described_class.new("INSERT").table_name).to be true }
![image](https://user-images.githubusercontent.com/3799140/49345086-3a59a380-f680-11e8-962c-83463591938e.png)


https://github.com/rubocop-hq/rubocop-rspec

2018-12-02 21:20 UTC, dmke commented on spec/unit/sql/query.rb
> +    it { expect(described_class.new("INSERT").table_name).to be true }
That... causes too much work :-)

2018-12-07 19:38 UTC, merged

2018-12-09 20:36 UTC, ChrisBr commented
Thanks for merging and releasing a new version :heart: And happy birthday (xing...) :cake: :tada:

2018-12-09 22:01 UTC, dmke commented
No problem (and thanks! 🎈)