use current timestamp instead of finished monotonic time
InfluxCommunity/influxdb-rails pull request #68
Opened 2019-06-12 13:43 UTC by hophacker

Normally, a developer expects a data point being inserted into influxdb with a timestamp of the current time. However, this project inserts a timestamp of the finished monotonic time which gets passed from rails' `ActiveSupport:: Notifications `([code](https://github.com/rails/rails/blob/master/activesupport/lib/active_support/notifications.rb)). 

This confused me a lot when I first received lots of timestampes like `717690.570250131`.... I calculated with lots of ways to figure out what does that timestamp mean, and finally managed to know that those timestamps are very close to the time since I reboot my mac. Then I searched and realized that `time since last reboot` has a term called `monotonic time`. I digged into rails source code and got to know that was happening.

I don't know what was the exact purpose of putting finished `monotonic time` into influxdb for timestamps, or it was just a small mistake.

Code fixed upon my issue, and tests all passed.

2019-06-27 14:05 UTC, ChrisBr commented
Hmm, that's interesting 🤔 I will dig into it ... Thanks for the PR!

2019-06-27 16:23 UTC, hophacker commented
Sure, I'm glad to make further changes

2019-07-03 21:47 UTC, ChrisBr commented
@hophacker I'm not sure were you think that the monotonic time is used 🤔 We use everywhere ``subscribe`` which uses ``monotonic: false`` (https://github.com/rails/rails/blob/master/activesupport/lib/active_support/notifications.rb#L235). Also it seems the term monotonic time in Rails context means not the time since rebooted but using an internal, more precise clock:

> A monotonic clock is a time source that won't ever jump forward or backward (due to NTP or Daylight Savings Time updates).

So not sure what your issue here is but I think our implementation is correct 🤔We should not use `current_timestamp` as this can be a lot later than the actual `finished` timestamp.

I also just tried this out in the specs and the correct current time gets written.

Could you maybe add some debug code here: 
https://github.com/influxdata/influxdb-rails/blob/master/lib/influxdb/rails/middleware/simple_subscriber.rb#L40
(like a 'puts finished`) and run `bundle exec rspec spec/integration/metrics_spec.rb`.

Long story, short: I do think the implementation is correct but happy to help debugging what is going on on your machine.

2019-07-03 21:50 UTC, ChrisBr commented on spec/unit/middleware/request_subscriber_spec.rb
> +          "rails.controller", data.deep_merge(values: { value: 2000 }, timestamp: InfluxDB::Rails.current_timestamp)
This is a source for flaky specs. Although this may succeed on your machine, it will be very flaky in CI as the time you merge in here won't be the same which got reported to `write_point` as it happened already a few `ms` before. You would need to freeze the time here.

2019-07-03 21:51 UTC, ChrisBr requested changes
See my other comment.

2019-07-04 02:05 UTC, hophacker commented
Sure, I'll check it out

2019-07-04 04:19 UTC, hophacker commented on spec/unit/middleware/request_subscriber_spec.rb
> +          "rails.controller", data.deep_merge(values: { value: 2000 }, timestamp: InfluxDB::Rails.current_timestamp)
All of the test failures are due to two cases
* syntax check failures of ruby code, I've corrected those failures and squashed into last commit
* default version of sqlite is `1.4.1`, which causes rails `5.0.x` and `4.2.x` to fail. I've fixed the version to be around `1.3.6` at the second commit. This will also let other PRs down if making requests of travis for them again.

2019-07-08 21:07 UTC, ChrisBr commented
Any update @hophacker ?

2019-07-09 03:25 UTC, hophacker commented
No any update, my last response was:
> All of the test failures are due to two cases

> syntax check failures of ruby code, I've corrected those failures and squashed into last commit
> default version of sqlite is 1.4.1, which causes rails 5.0.x and 4.2.x to fail. I've fixed the version to be around 1.3.6 at the second commit. This issue will also let other PRs down if making requests of travis for them again.

And I'm waiting for this PR to be merged or to be commented for further changes.

2019-07-09 08:15 UTC, ChrisBr commented
> And I'm waiting for this PR to be merged or to be commented for further changes.

See my comment here: https://github.com/influxdata/influxdb-rails/pull/68#issuecomment-508266187

Long story short: I doubt that our current code is wrong, please double check.

2019-09-30 05:51 UTC, ChrisBr commented
No response, closing

2019-09-30 05:51 UTC, closed without merging