[WIP] Drop Exceptions
InfluxCommunity/influxdb-rails pull request #78
Opened 2019-09-20 17:50 UTC by hennevogel

2019-09-30 05:51 UTC, ChrisBr requested changes

2019-09-30 05:51 UTC, ChrisBr commented on README.md
> -### What happens, when the InfluxDB client or this gem throws an exception? Will the user see 500 errors?
That's still valid? At least that you don't see an exception? I would still log them tho.

2019-09-30 05:51 UTC, ChrisBr commented on lib/influxdb-rails.rb
> -        InfluxDB::Logging.logger = configuration.logger unless configuration.logger.nil?
Would still log them, no? Otherwise it is quite hard to debug ...

2019-09-30 09:23 UTC, hennevogel commented on README.md
> -### What happens, when the InfluxDB client or this gem throws an exception? Will the user see 500 errors?
No it's not, this was part of the exception code. See the dropped `.report_exception` from `lib/influxdb-rails.rb`

2019-09-30 09:23 UTC, hennevogel commented on lib/influxdb-rails.rb
> -        InfluxDB::Logging.logger = configuration.logger unless configuration.logger.nil?
Yes we still log but just using `Rails.logger` directly...

2019-09-30 09:37 UTC, ChrisBr commented on README.md
> -### What happens, when the InfluxDB client or this gem throws an exception? Will the user see 500 errors?
Huh? We still wrap call into a `rescue` e.g. https://github.com/influxdata/influxdb-rails/blob/master/lib/influxdb/rails/middleware/simple_subscriber.rb#L18

2019-10-01 08:42 UTC, hennevogel commented on README.md
> -### What happens, when the InfluxDB client or this gem throws an exception? Will the user see 500 errors?
Added it again.

2019-10-01 12:38 UTC, ChrisBr commented on lib/influxdb/rails/middleware/request_subscriber.rb
> +          ::Rails.logger.error("[InfluxDB::Rails] Unable to write points: #{e.message}")
Is the escaping with `::` necessary?

2019-10-01 12:39 UTC, ChrisBr approved these changes
If you fix the specs 😉

2019-10-01 14:44 UTC, hennevogel commented on lib/influxdb/rails/middleware/request_subscriber.rb
> +          ::Rails.logger.error("[InfluxDB::Rails] Unable to write points: #{e.message}")
If you want this to be `Rails` and not `InfluxDB::Rails` I guess so...

2019-10-01 15:27 UTC, hennevogel commented
Here goes nothing...

2019-10-01 15:27 UTC, merged